# Generated by Django 5.1.6 on 2025-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_discussion_comment_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterialnotes',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
